name: flutter_mall
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # flutter的网络请求
  dio: ^3.0.9
  # flutter的轮播插件
  flutter_swiper: ^1.1.6
  # flutter的屏幕适配
  flutter_screenutil: ^1.0.2
  # 状态管理
  provide: ^1.0.2
  # toast
  fluttertoast: ^4.0.0
  # 拨打电话
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/avatar.png